### ISSUE TITLE
Share - 共用弹窗

### ISSUE THREAD

**Issue by Johnsonkk2020** [bookey-dev/bookey.prd#134]
# 需求

目的：统一分享入口，培养用户习惯

### 界面

- 分享共用弹窗

### 功能

- 分享的内容
   - 分享文字
   - 分享图片
- 分享的 APP
   - Instagram
   - Facebook
   - Twitter 
   - Whatsapp 
   - Messenger
   - Copy Link  More

### 逻辑

- 判断是否支持分享的类型：
   - 不支持隐藏该 APP 图标
- 判断是否已安装
   - 未安装隐藏该 APP 图标

## 备注

---

按钮排序
无法分享到INS的情况：
Facebook Twitter Whatsapp iMessage Messenger
Copy Link  More
可以分享到INS的情况
Instagram Facebook Twitter Whatsapp iMessage Messenger
Copy Link  More

---

Twitter
https://developer.twitter.com

Messenger
https://developers.facebook.com/docs/sharing/messenger#ios

Whatsapp
https://faq.whatsapp.com/iphone/how-to-link-to-whatsapp-from-a-different-app

Facebook
https://developers.facebook.com/docs/ios/getting-started

Ins
https://developers.facebook.com/docs/instagram/sharing-to-feed/

---

分享界面做个优化，如图。
有一个自定义的界面，把主流分享平台放前面，点other唤起系统分享界面。
![微信图片_20210123160729](https://user-images.githubusercontent.com/65063687/105572954-22c86200-5d95-11eb-9a49-e86a60d40d2f.jpg)

**Comment by itwangxiang** [comment]
太久没有处理，临时关闭
