### ISSUE TITLE
IWatch 开发

### ISSUE THREAD

**Issue by itwangxiang** [bookey-dev/bookey.prd#182]
### 描述

- [ ] daily free
- [ ] saved
- [ ] download
   - [ ] 点击直接删除
- [ ] categories
- [ ] 播放
   - [ ] 后台播放

### 备注

- 迭代处理
   - 同步音色
   - 删除本地的音频的确认框
   - 数据异常处理

## 任务

- [ ] IOS
- [ ] API

**Comment by Johnsonkk2020** [comment]
iwatch的播放器需要单独写，不能直接用苹果系统自带的。
