### ISSUE TITLE
新版 Me 页面

### ISSUE THREAD

**Issue by itwangxiang** [bookey-dev/bookey.prd#218]
### 描述

新版本 Me 页面

- 头像
- 累计 Finish 书籍
  - 点击后，进入已 mark 的记录列表（含 mark 的具体时间
- 累计使用APP时长
- 订阅面板
  - 会员信息
  - 详情入口
- 勋章入口
- 周报入口 #109

### 备注

api

- [library/mark](https://dev.bookey.app:8081/swagger-ui.html#/library-controller)

**Comment by Johnsonkk2020** [comment]
展示数据：
1、累计完成书籍数量
2、累计使用APP时长
@Hannah960906
