### ISSUE TITLE
google play 印度市场取消 - 免费试用的订阅产品

### ISSUE THREAD

**Issue by Johnsonkk2020** [bookey-dev/bookey.prd#277]
## 需求

因 google play 取消印度市场的免费试用订阅与续订的功能，做功能的调整

### 描述

针对印度用户，取消高低价试用产品，直接显示 other plan

### 备注

- 依据 google play 返回的产品价格单位来判断是否为印度用户

**Comment by itwangxiang** [comment]
暂不处理
