### ISSUE TITLE
优化礼品卡分享内容

### ISSUE THREAD

**Issue by Johnsonkk2020** [bookey-dev/bookey.prd#279]
## 需求
礼品卡详情页增加一点关于Bookey APP介绍的信息
### 描述
目前礼品卡详情页只有对礼品卡兑换的流程介绍，没有对APP本身做介绍，会有用户收到礼品卡后不知道是干嘛的，也不知道是什么APP.所以需要在详情页对APP做一点基本的介绍。

### 备注

???

**Comment by itwangxiang** [comment]
因礼品卡功能暂时隐藏，暂时关闭
