### ISSUE TITLE
新版 Focus areas（原 Me 页面的二级类目）

### ISSUE THREAD

**Issue by itwangxiang** [bookey-dev/bookey.prd#280]
## 需求

让用户更好了解自己感兴趣的领域

### 描述

从原 me 页面移植到独立的二级页面

UI

- 视觉优化

界面

- 展示一级类目的 mark 数
- 展示二级类目的学习情况（依据当前选定的一级类目下）

逻辑

- 点击二级类目图标，展示该二级类目的明细
  - 明细页支持跳转到对应的书籍类目页
- 点击一级类目图标切换当前展示的二级类目信息
  - 如果没有二级类目时，提示告知文案  - 由@Johnsonkk2020 提供

### 备注

新增功能

1. 切换类目时，增加LODAING动效 @Hannah960906 

2. 切换类目时，将其设置为默认类目（用户下次进入后，展示默认类目）

**Comment by Johnsonkk2020** [comment]
1、切换类目时，增加LODAING动效

2、切换类目时保存当前选择类目的状态（退出后重新进入时，展示最后保留的类目）
