### ISSUE TITLE
激活码调整为推荐码

### ISSUE THREAD

**Issue by itwangxiang** [bookey-dev/bookey.prd#303]
## 需求

目的：规避 IOS  审核

### 描述

1. 将设置页的激活码改为推荐码
   - 需提供推荐成功与失败的双语文案 - @Johnsonkk2020 
1. 移除礼品卡功能
   - > 移除首页 `me`  tab 的小红点通知机制
1. Deeplink - 移除礼品卡列表跳转 

### 备注

@Johnsonkk2020 提供推荐码标题的文案

| 错误码 | 错误码说明 | 英语提示文案 | 西语提示文案 |
| ------- | ------------ | ---------------| -------------|
| resource_not_found | 优惠券不存在 | ? | ? |
| voucher_disabled |优惠券已禁用| ? | ? |
| voucher_not_active | 优惠券暂未生效| ? | ? |
| voucher_expired | 优惠券已失效| ? | ? |
| customer_rules_violated | 当前用户不符合试用条件| ? | ? |
| quantity_exceeded | 当前用户已使用过| ? | ? |
| unknown_category | 优惠券未知分类| ? | ? |

**Comment by Johnsonkk2020** [comment]
错误码 | 错误码说明 | 英语提示文案 | 西语提示文案
-- | -- | -- | --
resource_not_found | 优惠券不存在 | ? | No se encontró este código de referencia.
voucher_disabled | 优惠券已禁用 | ? | No se encontró este código de referencia.
voucher_not_active | 优惠券暂未生效 | ? | No se encontró este código de referencia.
voucher_expired | 优惠券已失效 | ? | No se encontró este código de referencia.
customer_rules_violated | 当前用户不符合试用条件 | ? | No se encontró este código de referencia.
quantity_exceeded | 当前用户已使用过 | ? | Ya ha vinculado con un código de referencia, no puede hacerlo otra vez.
unknown_category | 优惠券未知分类 | ? | No se encontró este código de referencia.


绑定成功
西语：
¡Éxito en vincular con código de referencia!

**Comment by itwangxiang** [comment]
#306 搜索代替
