### ISSUE TITLE
订阅成功后的返回界面优化

### ISSUE THREAD

**Issue by Johnsonkk2020** [bookey-dev/bookey.prd#324]
# 需求

目的：提升用户体验

### 界面

订阅

### 功能

- 订阅完成后，均可以返回到一个特定界面，比如Discover或者Me页面（大家可以再商量确定下），但目前都是没有变化 ，会给人造成困惑有没有成功。

### 逻辑

- ?

## 备注

???

**Comment by itwangxiang** [comment]
太久没处理
