### ISSUE TITLE
搜索输入折扣订阅码时，先调起一个说明页

### ISSUE THREAD

**Issue by Johnsonkk2020** [bookey-dev/bookey.prd#328]
# 需求

目的：让用户更清楚地了解订阅后的权限

### 界面

- 输入订阅激活码后先唤起一个说明页

### 功能

- 输入订阅激活码后先唤起一个说明页

### 逻辑

- 输入订阅激活码后先唤起一个说明页

## 备注

???

**Comment by itwangxiang** [comment]
@Johnsonkk2020 这个还需要处理吗，我临时关闭了
