### ISSUE TITLE
思维导图app优化

### ISSUE THREAD

**Issue by Hannah960906** [bookey-dev/bookey.prd#329]
在顶部添加一张图片
![image](https://user-images.githubusercontent.com/49020343/124449533-233e3d80-ddb6-11eb-94a6-a29c20bbf0c9.png)

**Comment by Coolll** [comment]
规则
[(图片名)]书名##KeyInsight1标题_内容1_内容2##KeyInsight3标题_内容1_内容2##KeyInsight3标题_内容1_内容2....

图片名
    支持完整的Http链接
    支持仅输入文件名，会自动填充https://s3.us-west-2.amazonaws.com/bookey.push.media/mindmap/

书名、KeyInsight1、KeyInsight2、KeyInsight3...等为不同模块。

不同模块的分隔符为##

示例：
[(https://upload-images.jianshu.io/upload_images/9830379-1bbf4a66a4d0a064.jpg)]Grit##Grit, the combination of passion and perseverance._The Grit Scale at West Point_Grit matters more than talent_The quadratic relation between effort and achievement##Why is perseverance important?_The Mundanity of Excellence_Perseverance and deliberate practice lead to breakthroughs_“Extracurricular activities” and the “Hard Thing Rule”##Why is passion important?_Three attitudes to occupation_Slowly approaching a life mission_Connecting your goal with the world


[(Genghis+Khan+and+the+Making+of+the+Modern+World!.jpg)]Grit##Grit, the combination of passion and perseverance._The Grit Scale at West Point_Grit matters more than talent_The quadratic relation between effort and achievement##Why is perseverance important?_The Mundanity of Excellence_Perseverance and deliberate practice lead to breakthroughs_“Extracurricular activities” and the “Hard Thing Rule”##Why is passion important?_Three attitudes to occupation_Slowly approaching a life mission_Connecting your goal with the world
