### ISSUE TITLE
一级分类及二及分类，按不同语言执行不同展示逻辑

### ISSUE THREAD

**Issue by Johnsonkk2020** [bookey-dev/bookey.prd#348]
# 需求

目的：解决因书籍不全导致的内容为空问题

### 界面

- discover

### 功能

- 当OS后台没有输入一级类目或二级类目的字段名称时，前端对该分类标签不进行展示。

### 逻辑

- ?

## 备注

???

**Comment by itwangxiang** [comment]
已处理，可以通过多语言类目状态控制
