### ISSUE TITLE
咨询模板

### ISSUE THREAD

**Issue by Johnsonkk2020** [bookey-dev/bookey.prd#363]
# 需求

### 逻辑

- 咨询模板
- 以Messsage的形式发送给用户
- 模板形式：顶部为一个Banner，所有咨询共用一个，类似某个栏目的头图。下面为咨询的标题与正文。底部为推荐的一本书。

## 备注

@Hannah960906

**Comment by Hannah960906** [comment]
资讯模板

**Comment by itwangxiang** [comment]
#372
