### ISSUE TITLE
通知 - 模板 - 推送一个月试用订阅兑换码邮件

### ISSUE THREAD

**Issue by Johnsonkk2020** [bookey-dev/bookey.prd#368]
## 👀 需求说明（示例#366）

发送 一个月试用订阅兑换码 邮件给用户

### 用户故事(User Story)

作为 ...
 
我希望 ...

以便 ...

### 笔记(Note)

目标人数

- 取消试用的用户，及长时间未体验过会员的用户

推送逻辑

- 用户选择了7天试用订阅，且在试用期间取消了订阅，试用到期后的第一天给用户推送此Email及Message
- 用户没有选择任何产品，一直保持非会员状态至注册后第8天，给用户推送此Email及Message

## 🎯 需求目的（解决什么痛点，带来什么收益）

再次激活未订阅用户，提升订阅率。

## 🧾 需求来源（用户，竞品，运营，其他）

运营

## 📦 设计及资源（设计稿，相关资源，流程图）

...

## 💬 现有的问题

...

## ⚙️ 技术相关

...

**Comment by itwangxiang** [comment]
需求待确认，暂时关闭
