### ISSUE TITLE
Discover 页 - UI 排版优化

### ISSUE THREAD

**Issue by Johnsonkk2020** [bookey-dev/bookey.prd#389]
## 👀 需求说明（示例#366）

Discover 页 - UI 排版优化

### 用户故事(User Story)

作为 ...
 
我希望 ...

以便 ...

### 笔记(Note)

UI

- 将 **类目** 与 **书籍** 控件作对齐处理

## 🎯 需求目的（解决什么痛点，带来什么收益）

...

## 🧾 需求来源（用户，竞品，运营，其他）

...

## 📦 设计及资源（设计稿，相关资源，流程图）

...

## 💬 现有的问题

...

## ⚙️ 技术相关

...

**Comment by itwangxiang** [comment]
@Hannah960906 @Johnsonkk2020 

该需求未确定，暂时关闭
