### ISSUE TITLE
Search - 搜索功能结果展示优化 - 待讨论

### ISSUE THREAD

**Issue by Johnsonkk2020** [bookey-dev/bookey.prd#390]
## 👀 需求说明（示例#366）

搜索功能结果展示优化，展示更丰富合理内容

### 用户故事(User Story)

作为用户想要搜索APP里的内容
 
我希望输入关键词后可以跳出APP所有有关关键词的内容

以便 可以更全面地打到想要的信息

### 笔记(Note)

用户输入关键词后，我们匹配所有相关内容，包括标题、副标题、作者简介、书籍简介，以及正文内容。
结果展示时，以上述顺序进行展示。如果是在正文中有匹配，可以换一种展示形式，告诉用户具体在哪本书的哪一章，点击直接跳转到对应关键词处。

## 🎯 需求目的（解决什么痛点，带来什么收益）

...

## 🧾 需求来源（用户，竞品，运营，其他）

...

## 📦 设计及资源（设计稿，相关资源，流程图）

...

## 💬 现有的问题

...

## ⚙️ 技术相关

...

**Comment by itwangxiang** [comment]
太久没处理，已归档
