### ISSUE TITLE
新增一个deeplink跳转规则，点击咨询消息后跳转到咨询详情页

### ISSUE THREAD

**Issue by Johnsonkk2020** [bookey-dev/bookey.prd#396]
## 👀 需求说明（示例#366）

新增一个deeplink跳转规则，点击消息后跳转到消息列表

### 用户故事(User Story)

作为 ...
 
我希望 ...

以便 ...

### 笔记(Note)

用户出到**_咨询_**message的消息推送后，点击**_咨询_**消息后，跳转到对应的咨询内容页。

## 🎯 需求目的（解决什么痛点，带来什么收益）

...

## 🧾 需求来源（用户，竞品，运营，其他）

...

## 📦 设计及资源（设计稿，相关资源，流程图）

...

## 💬 现有的问题

ios

- [x] iPhone 收到资讯系统通知时，点击不能跳转到资讯详情

## ⚙️ 技术相关

...

**Comment by itwangxiang** [comment]
为 #372 补充需求
