### ISSUE TITLE
优化-书籍详情页二级类目标签跳转后的列表页展示优化

### ISSUE THREAD

**Issue by Johnsonkk2020** [bookey-dev/bookey.prd#398]
## 👀 需求说明（示例#366）

书籍详情页二级类目标签跳转后的列表页展示优化

### 用户故事(User Story)

作为 ...
 
我希望 ...

以便 ...

### 笔记(Note)

目前详情页二级分类跳转后的列表页为只有单个标签
![af289f2ced96cdf5413e6cffd506233](https://user-images.githubusercontent.com/65063687/134789862-87dd86a2-8cb1-4da6-af68-1bb4be6fa724.jpg)

需要优化为与点击一级分类下的二级分类列表一致
![2c39173c11a1b84d68c92e8a1625a83](https://user-images.githubusercontent.com/65063687/134790018-c28149a0-b28d-4d8d-92fd-ce9db8ab7883.jpg)

## 🎯 需求目的（解决什么痛点，带来什么收益）

...

## 🧾 需求来源（用户，竞品，运营，其他）

...

## 📦 设计及资源（设计稿，相关资源，流程图）

...

## 💬 现有的问题

...

## ⚙️ 技术相关

...

**Comment by itwangxiang** [comment]
与 #379 重复
