### ISSUE TITLE
设置页 - 推送通知 - 新增资讯类推送开关

### ISSUE THREAD

**Issue by itwangxiang** [bookey-dev/bookey.prd#404]
## 👀 需求说明（示例#366）

推送通知管理 - 新增是否接收资讯类推送开关

### 用户故事(User Story)

作为 ...
 
我希望 ...

以便 ...

### 笔记(Note)

- 设置页
   - 推送通知
      - 新增资讯类推送开关

> PS: 只是控制是否发送推送，不会影响消息的正常送达

## 🎯 需求目的（解决什么痛点，带来什么收益）

让用户自行选择是否接受资讯消息的推送，防止被打扰而关闭推送权限

## 🧾 需求来源（用户，竞品，运营，其他）

运营

## 📦 设计及资源（设计稿，相关资源，流程图）

...

## 💬 现有的问题

...

## ⚙️ 技术相关

API

- [setPushPrefUsingPOST](https://dev.bookey.app:8080/doc.html#/notify/notify-task-controller/setPushPrefUsingPOST)
   - notifyNews: true/flase - 是否接受资讯推送

**Comment by Hannah960906** [comment]
<meta charset='utf-8'>
      
      <style type="text/css">
        table { border-collapse: collapse; }
        br { mso-data-placement: same-cell; }
        tr { height: 21px; }
        td { overflow: hidden; padding:2px 3px 2px 3px; width: 100px; white-space: nowrap; }
        .s-3 { border-left:0.5pt solid #000000;border-top:0.5pt solid #000000;border-right:0.5pt solid #000000;border-bottom:0.5pt solid #000000; }

      </style>
      

Bookey Trends | Tendances de Bookey | Tendencias de Bookey
-- | -- | --
Receive trending news | Recevez des nouvelles tendances | Recibir noticias de actualidad

**Comment by Hannah960906** [comment]
英 | 法 | 西
-- | -- | --
Bookey Trends | Tendances de Bookey | Tendencias de Bookey
Receive trending news | Recevez des nouvelles tendances | Recibir noticias de actualidad
