### ISSUE TITLE
FOR YOU-西语/法语-书籍下方的标签仍为英语

### ISSUE THREAD

**Issue by Johnsonkk2020** [bookey-dev/bookey.prd#413]
**描述错误**
FOR YOU-西语/法语-书籍下方的标签仍为英语

**复现步骤**

**预期行为**
FOR YOU-西语/法语-书籍下方的标签应该为西语/法语

**截图**
![IMG_0022](https://user-images.githubusercontent.com/65063687/136882973-9628d58e-5b21-4060-bb90-5fbb0a41537b.PNG)

**设备**
  - 设备：[例如 iPhone 6]
  - 操作系统：[例如 iOS8.1]
  - 版本 [例如 v1.12.1]

**附加上下文**
![IMG_0022](https://user-images.githubusercontent.com/65063687/136882973-9628d58e-5b21-4060-bb90-5fbb0a41537b.PNG)

**Comment by itwangxiang** [comment]
api  问题，已处理
