### ISSUE TITLE
处理 Google Play 是否需要声明登录凭据

### ISSUE THREAD

**Issue by itwangxiang** [bookey-dev/bookey.prd#491]
### 👀 概要

处理 Google Play 是否需要声明登录凭据

### 🎯 目的

解决 Google play 的建议

### 🧾 描述

![2d0fd33574766a09c439c94d7bbf8eb](https://user-images.githubusercontent.com/7286154/147302521-90130739-fc90-4f67-967e-ad5cb64de492.jpg)

### 📦 设计及资源

.

### ⚙️ 技术相关

.

### 💬 现有的问题

.

**Comment by Maxkinger** [comment]
已添加相关说明
