### ISSUE TITLE
阅读 - 支持横屏模式 

### ISSUE THREAD

**Issue by Johnsonkk2020** [bookey-dev/bookey.prd#501]
### 👀 概要

阅读界面支持横屏模式

### 🎯 目的

为了让用户更方便地进行阅读体验

### 🧾 描述

阅读界面支持横屏模式，可通过IPAD或手机的放置状态自动感应横屏和竖屏，也可以通过按钮进行横屏和竖屏的切换。（是否需要按钮待Hannar确定）

### 📦 设计及资源

.

### ⚙️ 技术相关

.

### 💬 现有的问题

.

**Comment by Hannah960906** [comment]
在navbar添加切换横竖屏按钮，详见蓝湖

**Comment by xunmingtan** [comment]
阅读页面修改之前所有阅读页面相关控件。
