### ISSUE TITLE
华为 - 账号 - 用户信息出现vistor@bookey

### ISSUE THREAD

**Issue by Johnsonkk2020** [bookey-dev/bookey.prd#549]
### 描述错误
用户信息出现vistor@bookey
出现过程
下载安装--跳过登录--Boarding--订阅界面--试用订阅--订阅成功--进入APP--进入ME
![540047835731723004](https://user-images.githubusercontent.com/65063687/157173473-d5522026-2f32-4218-886f-3a2bb0774768.jpg)

### 期望结果
没有账号信息，显示的为sign in界面

**Comment by itwangxiang** [comment]
API 已做处理，游客将不返回数据

- 旧版本 Me 页面顶部将无法获取关于书籍类目 Focus Area
