### ISSUE TITLE
popular 和 for you书籍推荐逻辑优化

### ISSUE THREAD

**Issue by Johnsonkk2020** [bookey-dev/bookey.prd#83]
### 描述

popular的书籍可以依据完播率进行推荐，取10本点击超过100人，完播率高于90%的书
for you的书籍可以依据用户finish书籍类目进行推荐，首先推荐finish最多的类目的书，10本。如果finish是0，推荐个人发展类的书，如果有两个以上类目finish相同，随机取两个类目，平均分配5本书籍，

### 备注

???

## 任务

- [ ] API

**Comment by itwangxiang** [comment]
需求太久远，不做处理
